name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Replace token
        run: |
          sed -i "s|\$PR_TOKEN|${{ secrets.PR_TOKEN }}|g" src/services/github.ts

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "out/*"
          target: /var/www/html/vguessr
